---
title: "Compute autocorrelation functions in mother machine data"
output: 
  html_document:
    number_sections: TRUE
---

# How to use this Rmd document

A dataset (tibble format) should be loaded in the environmen. Its variable name should be "mydata".
Within mydata, cells are identified, unambiguously, by:
- the date of the experiment: date
- the position in the microscopy dataset: pos
- the orientation of its growth lane (top or bottom): orientation
- the number of the growth lane



The dataset should have the following fields, with the following format and units.
- time_sec : as double(), time at which the measurement was performed (seconds)
- condition : as.character(), describes the condition (e.g the name of the medium in which the cells grew)
- lane_id : as.character(), unique identifier of a growth lane (usually this is date.position.orientation.growthlane)
- cell_id: as.integer(), if the lane is known, this unambiguously identifies a single cell.
- cell: as.character(), unique identifier for a cell (usually this is date.position.orientation.growthlane.id, or lane_id.cell_id)
- growth_rate : as.double(), instantaneous single-cell exponential growth-rate in min-1
- parent_id: as.integer(), designates the parent of the cell

- trace_ref: as.character(), 
- mean_div_time:
- dt : 
- N: 


## A subtitle
## Another subtitle

# Another title